version = "Two"
max_width = 150
indent_style="Visual"
enum_discrim_align_threshold = 10
match_block_trailing_comma=true
imports_granularity="Crate"
ignore = []
edition = "2021"
hard_tabs = false
tab_spaces = 2
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
# normalize_comments = true
normalize_doc_attributes = true
# wrap_comments = true
