version = "Two"
unstable_features = true
max_width = 150
use_small_heuristics="Max"
indent_style="Visual"
enum_discrim_align_threshold = 10
group_imports="StdExternalCrate"
imports_granularity="Crate"
ignore = []
edition = "2021"
reorder_imports = false
reorder_modules = false
merge_derives = true
where_single_line = true
# fn_call_width = 120
wrap_comments=false
condense_wildcard_suffixes=true
format_macro_matchers=true

trailing_comma="Vertical"
match_block_trailing_comma = false