version = "Two"
max_width = 150
indent_style="Visual"
enum_discrim_align_threshold = 10
match_block_trailing_comma=true
imports_granularity="Crate"
ignore = []
edition = "2021"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
merge_derives = true
